import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import FooterPage from "@/Components/Footer";
import ExerciseProvider from "@/Context/ExerciseContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
    >
      <body className=" flex flex-col">
        <ExerciseProvider>
          <NavBar />
          {children}
          <FooterPage />
          <ToastContainer position="top-right" autoClose={2500} theme="dark" />
        </ExerciseProvider>
      </body>
    </html>
  );
}
